# This is a work-in-progress. For now we do not yet release the
# code when tagging a new release.
name: hexpm-release
on: [push]
# on:
#   push:
#     tags: [1-9]+.[0-9]+.[0-9]+
#     branches: master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: gleam-lang/setup-erlang@v1.1.2
        with:
          otp-version: 22.1
      - run: rebar3 eunit
